/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoScrollButton: typeof import('./src/components/AutoScrollButton/AutoScrollButton.vue')['default']
    Sample: typeof import('./src/components/AutoScrollButton/Sample.vue')['default']
  }
}
